general.import = ["~/.config/alacritty/kanagawa_dragon.toml"]


[window]
opacity = 0.7
[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "regular" }
