local Plug = vim.fn["plug#"]

vim.call("plug#begin")
Plug("vim-airline/vim-airline")
Plug("vim-airline/vim-airline-themes")
Plug("fatih/vim-go")
Plug("scrooloose/nerdtree")
Plug("xuyuanp/nerdtree-git-plugin")
Plug("ryanoasis/vim-devicons")
Plug("lukas-reineke/indent-blankline.nvim")
Plug("nvim-treesitter/nvim-treesitter")
Plug("nvim-lua/plenary.nvim")
Plug("nvim-telescope/telescope.nvim")
Plug("vim-test/vim-test")
Plug("mfussenegger/nvim-jdtls")
Plug("thesimonho/kanagawa-paper.nvim")
Plug("stevearc/conform.nvim")
Plug("numToStr/Comment.nvim")
Plug('brenoprata10/nvim-highlight-colors')
vim.call("plug#end")
